# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  DwarfAndBlade_config = debug

else ifeq ($(config),release)
  DwarfAndBlade_config = release

else ifeq ($(config),dist)
  DwarfAndBlade_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := DwarfAndBlade

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DwarfAndBlade:
ifneq (,$(DwarfAndBlade_config))
	@echo "==== Building DwarfAndBlade ($(DwarfAndBlade_config)) ===="
	@${MAKE} --no-print-directory -C . -f DwarfAndBlade.make config=$(DwarfAndBlade_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f DwarfAndBlade.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DwarfAndBlade"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"