# This is a basic workflow to help you get started with Actions

name: DwarfAndBlade GCC Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ CI-release-branch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # Add Msys2 and aquire packages
    - name: Add Msys2
      uses: numworks/setup-msys2@v1
      with: 
        update: true
        msystem: MSYS

    - run: msys2do pacman -Sy mingw64/mingw-w64-x86_64-gcc
    - run: msys2do pacman -Sy msys/gcc
    - run: msys2do pacman -Sy mingw64/mingw-w64-x86_64-glfw

    #test gcc works
    - run: msys2do gcc 

    #test make works
    - run: msys2do make

    